import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "../lib/AntdRegistry";
import Header from "@/component/header";
import Footer from "@/component/footer";
import Online from "@/component/online";
import Contact from "@/component/contact";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "website",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <StyledComponentsRegistry>
                    <Header />
                    <div>{children}</div>
                    <Online/>
                    <Contact/>
                    <Footer/>
                </StyledComponentsRegistry>
            </body>
        </html>
    );
}
